version: '2.1'

services:
  odc:
    image: web
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
